[EvilGod]
title = "The title"
url = "https://manhuaus.com/?s=Wo+Wei+Xie+Di&post_type=wp-manga"
entrySelector = ".c-tabs-item__content"
titleSelector = ".latest-chap span"
linkSelector = ".latest-chap span a"
waitUntil = "networkidle"
onFail = "skip"

[EvilGod2]
title = "The title2"
url = "https://manhuaus.com/manga/im-an-evil-god/"
entrySelector = "ul.main"
titleSelector = "li.wp-manga-chapter"
linkSelector = "li.wp-manga-chapter a"
waitForSelector = "div#manga-discussion"
waitUntil = "networkidle"
onFail = "skip"
