[EvilGod]
title = "The title"
url = "https://manhuaus.com/?s=Wo+Wei+Xie+Di&post_type=wp-manga"
entrySelector = ".c-tabs-item__content"
titleSelector = ".latest-chap span"
linkSelector = ".latest-chap span a"
waitForSelector = ".latest-chap span a"
waitUntil = "networkidle"
onFail = "stale"
