[EvilGod]
title = "I’m An Evil God"
url = "https://manhuaus.com/?s=Wo+Wei+Xie+Di&post_type=wp-manga"
entrySelector = ".c-tabs-item__content"
titleSelector = ".latest-chap span a"
linkSelector = ".latest-chap span a"
