[EvilGod]
title = "The title"
url = "https://manhuaus.com/?s=Wo+Wei+Xie+Di&post_type=wp-manga"
entrySelector = ".c-tabs-item__content"
titleSelector = ".latest-chap span"
linkSelector = ".latest-chap span a"
waitUntil = "networkidle"
onFail = "error"

[EvilGod2]
title = "The title2"
url = "https://manhuaus.com/manga/im-an-evil-god/"
entrySelector = "ul.main"
titleSelector = "li.wp-manga-chapter"
linkSelector = "li.wp-manga-chapter a"
waitUntil = "networkidle"
onFail = "error"

[EvilGod3]
title = "I'm an Evil God"
url = "https://mangahub.io/manga/i-m-an-evil-god/"
entrySelector = "ul.list-group"
titleSelector = "a span"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "error"
